[env]
TERM = "xterm-256color"

# Window settings
[window]
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"
blur = true

[window.dimensions]
columns = 80
lines = 24

[window.position]
x = 0
y = 0

[window.padding]
x = 3
y = 4


# Font settings
[font]
size = 11.5



[font.normal]
family = 'Hasklig'
style = 'Regular'
[font.bold]
family = 'Hasklig'
style = 'Bold'

# Colors (Rose Pine color scheme)
[colors]
[colors.primary]
background ='0x000000'   # Black
foreground = '0xd3d3d3'   # Light Gray

#background = "0x191724"
#foreground = "0xe0def4"

[colors.cursor]
text = "0x191724"
cursor = "0xe0def4"

[colors.normal]
black = "0x191724"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0x9ccfd8"
white = "0xe0def4"

[colors.bright]
black = "0x524f67"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0x9ccfd8"
white = "0xe0def4"

# Cursor settings
[cursor]

[cursor.style]
shape = "Block"
blinking = "Never"

# Selection colors
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[mouse]
hide_when_typing = true


[[hints.enabled]]
regex = "(http|https)://\\S+"
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "None"

